// src/app/layout.tsx
import type { Metadata } from "next";
// Remove the old 'next/font/google' imports for Geist
// import { Geist, Geist_Mono } from "next/font/google"; // DELETE THIS LINE

import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "./globals.css";
import 'katex/dist/katex.min.css'; // Your KaTeX CSS
import { Toaster } from "sonner";
import { AppSidebar } from "@/components/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { Separator } from "@/components/ui/separator"; // Assuming this is still used somewhere

// No need to call GeistSans() or GeistMono() like with next/font/google
// The package handles providing the CSS variables and font loading.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}> {/* Apply variables to <html> */}
      <body className="antialiased"> {/* antialiased can stay on body */}
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-12 items-center px-4 sticky top-0 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 z-10 border-b">
              <SidebarTrigger className="-ml-1" />
            </header>
            <main className="flex-1 overflow-y-auto p-4 md:p-6 lg:p-8">
              {children}
              <Toaster />
            </main>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
